name: Send Repo Name

on:
  push:
    tags:
      - v1.**

jobs:
  send-repo-name:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AUTH_GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Send assignment submit result to SQL Database
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 5
          command: | 
            node ./tests/send-assignment-submit-result-script.js ${{ github.repository }}